# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoJSONSketchpad
                                 A QGIS plugin
 Provides a sketchpad for coding GeoJSON
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-24
        copyright            : (C) 2022 by David Caplin
        email                : David.CaplinUK@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoJSONSketchpad class from file GeoJSONSketchpad.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgis3_geojson_sketch import GeoJSONSketchpad
    return GeoJSONSketchpad(iface)
